In [1]:
import numpy as np

In [2]:
a = np.arange(1,4)
print(a)

[1 2 3]


In [3]:
b = np.arange(5,11,2)
print(b)

[5 7 9]


In [4]:
c = np.arange(11,5,-2)
print(c)

[11  9  7]


In [5]:
a[1:3]

array([2, 3])

In [6]:
a + b

array([ 6,  9, 12])

In [7]:
a - b

array([-4, -5, -6])

In [8]:
a * b

array([ 5, 14, 27])

In [9]:
a / b

array([0.2       , 0.28571429, 0.33333333])